import curses

FLOOR_WIDTH = 100
FLOOR_HEIGHT = 50
MIN_ROOMS = 3
MAX_ROOMS = 9
MIN_ROOM_WIDTH = 5
MAX_ROOM_WIDTH = 20
MIN_ROOM_HEIGHT = 5
MAX_ROOM_HEIGHT = 10
MIN_ENEMIES = 1
MAX_ENEMIES = 4
MIN_THINGS = 0
MAX_THINGS = 5
STARTING_WEAPON_TYPE = 0
STARTING_WEAPON_MODS = (1, 1)
STARTING_ARMOR_TYPE = 1

PLAYER_NAME = "Player"